### ISSUE TITLE
Starting or stopping multiple instances of same account

### ISSUE THREAD

**Issue by sincerekamal** [phstc/amazon_start_stop#1]
Hi, is this project gives the flexibility to start/stop multiple EC2 instance which are each associated with elastic IP ?

**Comment by phstc** [comment]
Hey @sincerekamal 

It stops and starts instances based on their IDs, not on the their IPs. 

https://github.com/phstc/amazon_start_stop/blob/master/bin/amazon_start_stop#L12

Thanks

**Comment by sincerekamal** [comment]
My doubt not answered properly yet. My question is about starting/stopping multiple instance from same server, not about using elastic IP with that.

**Comment by phstc** [comment]
Hi @sincerekamal 

Not sure if I understood your question properly. How do you group multiple instances for the same server? What do you call "server" in this case? Is that an ELB?

You can't have multiple instances associated with an Elastic IP in Amazon.

**Comment by sincerekamal** [comment]
My Question is not about elastic IP or ELB. To be more clear and simple,

**Can I stop multiple instances from a single server or heroku app ?**

**Comment by phstc** [comment]
Hi @sincerekamal 

Now I understood what you mean by server. Thanks!

In the current way it's, you can't. But the change would be straightforward:

Basically changing [this](https://github.com/phstc/amazon_start_stop/blob/master/bin/amazon_start_stop#L12) to:

``` ruby
ENV['AWS_INSTANCE_ID'].split(',').map(&:strip).each do |instance_id|
  server = conn.servers.get(instance)

  ...
end
```

So instead of setting a single instance id, you can set multiple ones, delimited by `,`.

If you are using Elastic IP, you will need to change [this](https://github.com/phstc/amazon_start_stop/blob/master/bin/amazon_start_stop#L42-L47) too.

Let me know if I can help you with anything else.
